import { selectInterviewTopics } from "./interviewPlanner.js";

import {
  createInterviewSession,
  addAssistantMessage,
  addCandidateMessage,
  incrementQuestion,
  getCurrentTopic,
  moveToNextTopic,
  canFinishInterview,
} from "./interviewController.js";

const sessions = new Map();


// Temporary question generator.
// We will replace this with the LLM later.
function generateQuestion(topic, questionNumber) {
  const questions = [
    `Let's start with ${topic.title}. Can you explain the main concept in your own words?`,

    `What problem does ${topic.title} solve, and why is it useful?`,

    `Can you give me a practical example related to ${topic.title}?`,

    `What are some important technical considerations when working with ${topic.title}?`,

    `How would you apply ${topic.title} in a real-world AI application?`,

    `What challenges could you face when implementing ${topic.title}?`,
  ];

  return questions[
    questionNumber % questions.length
  ];
}


// START INTERVIEW
export function startInterview(
  sessionId,
  candidate,
  curriculum
) {
  const topics = selectInterviewTopics(
    candidate,
    curriculum
  );

  const session = createInterviewSession(
    sessionId,
    candidate,
    topics
  );

  sessions.set(sessionId, session);

  const firstTopic = getCurrentTopic(session);

  // Mark the first curriculum day as covered.
  session.topicsCovered.add(firstTopic.day);

  const firstQuestion = generateQuestion(
    firstTopic,
    session.questionCount
  );

  incrementQuestion(session);

  addAssistantMessage(
    session,
    firstQuestion
  );

  return {
    reply: firstQuestion,
    done: false,
  };
}


// CONTINUE INTERVIEW
export function continueInterview(
  sessionId,
  message
) {
  const session = sessions.get(sessionId);

  if (!session) {
    throw new Error(
      "Interview session not found."
    );
  }

  // Save candidate's answer.
  addCandidateMessage(
    session,
    message
  );


  /*
    We do NOT finish the interview until:

    1. At least 8 questions have been asked.
    2. At least 4 curriculum days have been covered.
  */

  if (!canFinishInterview(session)) {

    /*
      For our temporary implementation,
      move to the next curriculum topic
      after every 2 questions.

      Later the AI will decide when
      a topic has been sufficiently explored.
    */

    if (
      session.questionCount % 2 === 0
    ) {
      const moved = moveToNextTopic(session);

      if (moved) {
        const newTopic =
          getCurrentTopic(session);

        session.topicsCovered.add(
          newTopic.day
        );
      }
    }

    const currentTopic =
      getCurrentTopic(session);

    const nextQuestion =
      generateQuestion(
        currentTopic,
        session.questionCount
      );

    incrementQuestion(session);

    addAssistantMessage(
      session,
      nextQuestion
    );

    return {
      reply: nextQuestion,
      done: false,
    };
  }


  // Interview requirements have been satisfied.
  session.done = true;

  const feedback =
    generateFeedback(session);

  sessions.delete(sessionId);

  return {
    reply: "Interview completed.",
    done: true,
    feedback,
  };
}


// Temporary feedback.
// Later this will be generated by the AI.
function generateFeedback(session) {
  return {
    summary:
      "The candidate completed a technical interview covering multiple curriculum topics.",

    strengths: [
      "Demonstrated understanding of technical concepts.",
      "Attempted questions across multiple curriculum areas.",
    ],

    gaps: [
      "Some answers could include more technical depth.",
    ],

    next: [
      "Practice explaining concepts with concrete examples.",
      "Review the curriculum topics covered during the interview.",
    ],
  };
}